spring:
  application:
    name: academics

  scholarships:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3306/mcs-scholarships?createDatabaseIfNotExist=true
      username: root
      password: password

  academics:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3306/mcs-academics?createDatabaseIfNotExist=true
      username: root
      password: password

  users:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3306/mcs-users?createDatabaseIfNotExist=true
      username: root
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true

server:
  port: 8083
