spring:
  application:
    name: academics

  datasource:
    url: jdbc:mysql://localhost:3306/mcs-admissions?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true

server:
  port: 8082
