spring:
  application:
    name: staff

  staff:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3306/mcs-staff?createDatabaseIfNotExist=true
      username: root
      password: password

  users:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3306/mcs-users?createDatabaseIfNotExist=true
      username: root
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true

server:
  port: 8084
